/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyGoalsRouteImport } from './routes/daily-goals'
import { Route as FocusPulseRouteImport } from './routes/focus-pulse'
import { Route as MicroStepRouteImport } from './routes/micro-step'
import { Route as SnippetsVaultRouteImport } from './routes/snippets-vault'
import { Route as MicroStepGoalIdRouteImport } from './routes/$goalId.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyGoalsRoute = DailyGoalsRouteImport.update({
  id: '/daily-goals',
  path: '/daily-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusPulseRoute = FocusPulseRouteImport.update({
  id: '/focus-pulse',
  path: '/focus-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroStepRoute = MicroStepRouteImport.update({
  id: '/micro-step',
  path: '/micro-step',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsVaultRoute = SnippetsVaultRouteImport.update({
  id: '/snippets-vault',
  path: '/snippets-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroStepGoalIdRoute = MicroStepGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => MicroStepRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-goals': typeof DailyGoalsRoute
  '/focus-pulse': typeof FocusPulseRoute
  '/micro-step': typeof MicroStepRouteWithChildren
  '/snippets-vault': typeof SnippetsVaultRoute
  '/micro-step/$goalId': typeof MicroStepGoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-goals': typeof DailyGoalsRoute
  '/focus-pulse': typeof FocusPulseRoute
  '/micro-step': typeof MicroStepRouteWithChildren
  '/snippets-vault': typeof SnippetsVaultRoute
  '/micro-step/$goalId': typeof MicroStepGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-goals': typeof DailyGoalsRoute
  '/focus-pulse': typeof FocusPulseRoute
  '/micro-step': typeof MicroStepRouteWithChildren
  '/snippets-vault': typeof SnippetsVaultRoute
  '/micro-step/$goalId': typeof MicroStepGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-goals'
    | '/focus-pulse'
    | '/micro-step'
    | '/snippets-vault'
    | '/micro-step/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily-goals'
    | '/focus-pulse'
    | '/micro-step'
    | '/snippets-vault'
    | '/micro-step/$goalId'
  id:
    | '__root__'
    | '/'
    | '/daily-goals'
    | '/focus-pulse'
    | '/micro-step'
    | '/snippets-vault'
    | '/micro-step/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyGoalsRoute: typeof DailyGoalsRoute
  FocusPulseRoute: typeof FocusPulseRoute
  MicroStepRoute: typeof MicroStepRouteWithChildren
  SnippetsVaultRoute: typeof SnippetsVaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-goals': {
      id: '/daily-goals'
      path: '/daily-goals'
      fullPath: '/daily-goals'
      preLoaderRoute: typeof DailyGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus-pulse': {
      id: '/focus-pulse'
      path: '/focus-pulse'
      fullPath: '/focus-pulse'
      preLoaderRoute: typeof FocusPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/micro-step': {
      id: '/micro-step'
      path: '/micro-step'
      fullPath: '/micro-step'
      preLoaderRoute: typeof MicroStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets-vault': {
      id: '/snippets-vault'
      path: '/snippets-vault'
      fullPath: '/snippets-vault'
      preLoaderRoute: typeof SnippetsVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/micro-step/$goalId': {
      id: '/micro-step/$goalId'
      path: '/$goalId'
      fullPath: '/micro-step/$goalId'
      preLoaderRoute: typeof MicroStepGoalIdRouteImport
      parentRoute: typeof MicroStepRoute
    }
  }
}

interface MicroStepRouteChildren {
  MicroStepGoalIdRoute: typeof MicroStepGoalIdRoute
}

const MicroStepRouteChildren: MicroStepRouteChildren = {
  MicroStepGoalIdRoute: MicroStepGoalIdRoute,
}

const MicroStepRouteWithChildren = MicroStepRoute._addFileChildren(
  MicroStepRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyGoalsRoute: DailyGoalsRoute,
  FocusPulseRoute: FocusPulseRoute,
  MicroStepRoute: MicroStepRouteWithChildren,
  SnippetsVaultRoute: SnippetsVaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
