/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalIdRouteImport } from './routes/$goalId'
import { Route as DailyGoalsRouteImport } from './routes/daily-goals'
import { Route as DevNexusRouteImport } from './routes/dev-nexus'
import { Route as FocusPulseRouteImport } from './routes/focus-pulse'
import { Route as MicroStepRouteImport } from './routes/micro-step'
import { Route as SnippetsVaultRouteImport } from './routes/snippets-vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalIdRoute = GoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyGoalsRoute = DailyGoalsRouteImport.update({
  id: '/daily-goals',
  path: '/daily-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DevNexusRoute = DevNexusRouteImport.update({
  id: '/dev-nexus',
  path: '/dev-nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusPulseRoute = FocusPulseRouteImport.update({
  id: '/focus-pulse',
  path: '/focus-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroStepRoute = MicroStepRouteImport.update({
  id: '/micro-step',
  path: '/micro-step',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsVaultRoute = SnippetsVaultRouteImport.update({
  id: '/snippets-vault',
  path: '/snippets-vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$goalId': typeof GoalIdRoute
  '/daily-goals': typeof DailyGoalsRoute
  '/dev-nexus': typeof DevNexusRoute
  '/focus-pulse': typeof FocusPulseRoute
  '/micro-step': typeof MicroStepRoute
  '/snippets-vault': typeof SnippetsVaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$goalId': typeof GoalIdRoute
  '/daily-goals': typeof DailyGoalsRoute
  '/dev-nexus': typeof DevNexusRoute
  '/focus-pulse': typeof FocusPulseRoute
  '/micro-step': typeof MicroStepRoute
  '/snippets-vault': typeof SnippetsVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$goalId': typeof GoalIdRoute
  '/daily-goals': typeof DailyGoalsRoute
  '/dev-nexus': typeof DevNexusRoute
  '/focus-pulse': typeof FocusPulseRoute
  '/micro-step': typeof MicroStepRoute
  '/snippets-vault': typeof SnippetsVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$goalId'
    | '/daily-goals'
    | '/dev-nexus'
    | '/focus-pulse'
    | '/micro-step'
    | '/snippets-vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$goalId'
    | '/daily-goals'
    | '/dev-nexus'
    | '/focus-pulse'
    | '/micro-step'
    | '/snippets-vault'
  id:
    | '__root__'
    | '/'
    | '/$goalId'
    | '/daily-goals'
    | '/dev-nexus'
    | '/focus-pulse'
    | '/micro-step'
    | '/snippets-vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalIdRoute: typeof GoalIdRoute
  DailyGoalsRoute: typeof DailyGoalsRoute
  DevNexusRoute: typeof DevNexusRoute
  FocusPulseRoute: typeof FocusPulseRoute
  MicroStepRoute: typeof MicroStepRoute
  SnippetsVaultRoute: typeof SnippetsVaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$goalId': {
      id: '/$goalId'
      path: '/$goalId'
      fullPath: '/$goalId'
      preLoaderRoute: typeof GoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-goals': {
      id: '/daily-goals'
      path: '/daily-goals'
      fullPath: '/daily-goals'
      preLoaderRoute: typeof DailyGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-nexus': {
      id: '/dev-nexus'
      path: '/dev-nexus'
      fullPath: '/dev-nexus'
      preLoaderRoute: typeof DevNexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus-pulse': {
      id: '/focus-pulse'
      path: '/focus-pulse'
      fullPath: '/focus-pulse'
      preLoaderRoute: typeof FocusPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/micro-step': {
      id: '/micro-step'
      path: '/micro-step'
      fullPath: '/micro-step'
      preLoaderRoute: typeof MicroStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets-vault': {
      id: '/snippets-vault'
      path: '/snippets-vault'
      fullPath: '/snippets-vault'
      preLoaderRoute: typeof SnippetsVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalIdRoute: GoalIdRoute,
  DailyGoalsRoute: DailyGoalsRoute,
  DevNexusRoute: DevNexusRoute,
  FocusPulseRoute: FocusPulseRoute,
  MicroStepRoute: MicroStepRoute,
  SnippetsVaultRoute: SnippetsVaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
